[package]
name = "helloworld"
version = "0.1.0"
authors = ["James Harmison <jharmison@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
nix = "0.20.0"
